name: Deploy Frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_KEY }}
      
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
      - name: Test Connection
        run: ssh numa-desarrollo@34.71.107.222 "echo 'Conexión SSH exitosa'"

      - name: Sync Files
        run: |
          rsync -avz --delete \
            -e "ssh -o BatchMode=yes" \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='.next' \
            --exclude='.cache' \
            --exclude='.vscode' \
            --exclude='.idea' \
            ./ numa-desarrollo@34.71.107.222:/home/numa-desarrollo/numa-reporteador-frontend

      - name: Update Frontend Service
        run: |
          ssh numa-desarrollo@34.71.107.222 << 'EOF'
          cd /home/numa-desarrollo
          chmod +x update-service.sh
          ./update-service.sh frontend
          EOF
